language:
  - cpp
  
python:
  - "2.7"
sudo: required

compiler:
  - gcc
  
before_install:
  # Gcc 4.8
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  # OmniORB 4
  - sudo apt-get install -y libomniorb4-dev omniidl libomniorb4* omni* libblas* liblapack* f2c omniidl-python omniorb-nameserver libomniorb4-1-dbg libomniorb4-dev omniorb omniorb-idl python-omniorb-dbg python-omniorb-doc
  # Define some config vars
  - export ROS_DISTRO=hydro
  - export CI_SOURCE_PATH=$(pwd)
  - export EXTRA_CMAKE_ARGS="-DENABLE_TESTS=OFF -DENABLE_CORBA=ON -DCORBA_IMPLEMENTATION=OMNIORB"
  # Install ROS
  - sudo sh -c "echo 'deb http://packages.ros.org/ros/ubuntu $(lsb_release -cs) main' > /etc/apt/sources.list.d/ros-latest.list"
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install ros-$ROS_DISTRO-desktop-full
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - sudo -E rosdep init
  - rosdep update
  # Install OROCOS Toolchain
  - export OROCOS_TARGET=gnulinux
  - mkdir -p ~/isolated_ws/src/orocos
  - cd ~/isolated_ws
  - git clone --recursive https://github.com/orocos-toolchain/orocos_toolchain -b toolchain-2.8 src/orocos/orocos_toolchain

install:
  - catkin_make_isolated --install -j1 --cmake-args $EXTRA_CMAKE_ARGS
  - source install_isolated/setup.sh
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - catkin_init_workspace
  - ln -s $CI_SOURCE_PATH
  - git clone https://github.com/orocos/rtt_ros_integration.git src/rtt_ros_integration
  - git clone https://github.com∕kuka-isir/ati_sensor
  - cd ~/catkin_ws
  - catkin_make -j1

script:
  - source devel/setup.bash
  - catkin_make -j1
